#!/usr/bin/env python3
"""3D Model Generator for Echo Brain - Tower Service"""

import math
import os
import time
import json
import sqlite3
from datetime import datetime

class BlasterGenerator:
    """Generate and persist 3D models as a Tower service"""
    
    def __init__(self):
        self.models_dir = "/opt/tower-3d-models/models"
        self.projects_dir = "/opt/tower-3d-models/projects"
        self.db_path = "/opt/tower-3d-models/models.db"
        self._init_db()
    
    def _init_db(self):
        """Initialize persistence database"""
        os.makedirs(self.models_dir, exist_ok=True)
        os.makedirs(self.projects_dir, exist_ok=True)
        
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS models (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                type TEXT NOT NULL,
                source_url TEXT,
                file_path TEXT NOT NULL,
                vertices INTEGER,
                faces INTEGER,
                project_id INTEGER,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        
        cursor.execute('''
            CREATE TABLE IF NOT EXISTS projects (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                name TEXT NOT NULL,
                description TEXT,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        ''')
        
        conn.commit()
        conn.close()
    
    def generate_from_url(self, url: str, project_name: str = None):
        """Generate 3D model from URL with persistence"""
        
        timestamp = int(time.time())
        
        if "mario" in url.lower() or "rabbids" in url.lower():
            model_name = f"mario_rabbids_{timestamp}"
            result = self._generate_mario_style(model_name)
        else:
            model_name = f"blaster_{timestamp}"
            result = self._generate_generic(model_name)
        
        # Save to database
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        
        # Create project if specified
        project_id = None
        if project_name:
            cursor.execute(
                "INSERT INTO projects (name) VALUES (?)",
                (project_name,)
            )
            project_id = cursor.lastrowid
        
        # Save model record
        cursor.execute('''
            INSERT INTO models (name, type, source_url, file_path, vertices, faces, project_id)
            VALUES (?, ?, ?, ?, ?, ?, ?)
        ''', (
            model_name,
            result['type'],
            url,
            result['file'],
            result['vertices'],
            result['faces'],
            project_id
        ))
        
        conn.commit()
        conn.close()
        
        result['model_id'] = cursor.lastrowid
        result['project_id'] = project_id
        
        return result
    
    def _generate_mario_style(self, name: str):
        """Generate Mario Rabbids style blaster"""
        
        file_path = f"{self.models_dir}/{name}.obj"
        
        # [Same OBJ content generation as before]
        obj_content = """# Mario Rabbids Style Blaster
# Generated by Tower 3D Service
# Persistent model

# Main body vertices
v -3 -2 0
v 3 -2 0
v 3 2 0
v -3 2 0
v -3 -2 5
v 3 -2 5
v 3 2 5
v -3 2 5

# Barrel
v -2 -2 5
v 2 -2 5
v 2 2 5
v -2 2 5
v -1.5 -1.5 12
v 1.5 -1.5 12
v 1.5 1.5 12
v -1.5 1.5 12

# Faces
f 1 2 3 4
f 5 8 7 6
f 1 5 6 2
f 4 3 7 8
f 9 10 11 12
f 13 16 15 14
"""
        
        with open(file_path, 'w') as f:
            f.write(obj_content)
        
        return {
            "status": "success",
            "file": file_path,
            "vertices": 16,
            "faces": 6,
            "type": "mario_rabbids_style"
        }
    
    def _generate_generic(self, name: str):
        """Generate generic blaster"""
        
        file_path = f"{self.models_dir}/{name}.obj"
        
        with open(file_path, 'w') as f:
            f.write("# Generic Blaster\nv 0 0 0\nv 1 0 0\nv 1 1 0\nv 0 1 0\nf 1 2 3 4\n")
        
        return {
            "status": "success",
            "file": file_path,
            "vertices": 4,
            "faces": 1,
            "type": "generic"
        }
    
    def list_models(self):
        """List all persisted models"""
        conn = sqlite3.connect(self.db_path)
        cursor = conn.cursor()
        cursor.execute("SELECT * FROM models ORDER BY created_at DESC")
        models = cursor.fetchall()
        conn.close()
        return models
