#!/usr/bin/env python3
"""
DeepSeek Coding Agent - Autonomous code improvement system
Executes via Echo Brain API with full repository access
"""
import os
import json
import subprocess
from typing import Dict, Any
import requests

class DeepSeekCodingAgent:
    def __init__(self):
        self.api_url = "http://localhost:8309/api/echo/chat"
        self.repo_path = "/opt/tower-echo-brain"

    def analyze_codebase(self) -> Dict[str, Any]:
        """Perform comprehensive codebase analysis"""
        print("🔍 Analyzing codebase structure...")

        # Run code quality tools
        metrics = {}

        # File count by type
        result = subprocess.run(
            ["find", self.repo_path, "-type", "f", "-name", "*.py"],
            capture_output=True, text=True
        )
        metrics["python_files"] = len(result.stdout.strip().split('\n')) if result.stdout else 0

        # Check for obvious issues
        issues = []

        # 1. Check for unwired theater files
        theater_files = ["auth_middleware.py", "rate_limiting.py", "pool_manager.py", "monitoring.py"]
        for tf in theater_files:
            tf_path = f"{self.repo_path}/src/middleware/{tf}"
            if os.path.exists(tf_path):
                # Check if imported in app_factory.py
                with open(f"{self.repo_path}/src/app_factory.py", 'r') as f:
                    content = f.read()
                    if f"import {tf[:-3]}" not in content and f"from .{tf[:-3]}" not in content:
                        issues.append(f"Theater file not wired: {tf}")

        # 2. Check context contamination potential
        with open(f"{self.repo_path}/src/middleware/memory_augmentation_middleware.py", 'r') as f:
            mw_content = f.read()
            if "global" in mw_content and "context" in mw_content:
                issues.append("Potential context contamination in memory middleware")

        return {
            "status": "analysis_complete",
            "metrics": metrics,
            "issues_found": issues,
            "priority_actions": [
                "Fix context contamination bug",
                "Wire up theater middleware",
                "Create verification test suite"
            ]
        }

    def execute_autonomous_fix(self, issue: str) -> Dict[str, Any]:
        """Use DeepSeek to generate and apply fixes"""
        print(f"🛠️  Generating fix for: {issue}")

        prompt = f"""
        As the DeepSeek Coding Agent, fix this issue in the Echo Brain system:
        ISSUE: {issue}

        REPOSITORY: /opt/tower-echo-brain/
        TECH STACK: Python 3.10+, FastAPI, SQLAlchemy, asyncpg

        Requirements:
        1. Generate working code with proper imports
        2. Include tests that verify the fix
        3. Create Git commit with descriptive message
        4. Show the diff before applying

        Provide only the JSON response with:
        - analysis: Brief problem analysis
        - solution: Proposed fix description
        - code_changes: Specific code modifications
        - test_plan: How to verify the fix works
        - commands: Shell commands to apply the fix
        """

        response = requests.post(
            self.api_url,
            json={
                "query": prompt,
                "intelligence_level": "deep",
                "agent_type": "DeepSeekCodingAgent"
            },
            timeout=120
        )

        if response.status_code == 200:
            return response.json()
        else:
            return {"error": f"API request failed: {response.status_code}"}

    def apply_fix(self, fix_data: Dict[str, Any]) -> bool:
        """Apply the generated fix autonomously"""
        try:
            # 1. Create backup
            subprocess.run(["git", "-C", self.repo_path, "stash"], check=False)

            # 2. Apply code changes (simplified - in reality would parse diff)
            if "code_changes" in fix_data:
                print("📝 Applying code changes...")
                # This would be more sophisticated in production
                # For now, we'll create a fix file
                fix_file = "/tmp/autonomous_fix.py"
                with open(fix_file, 'w') as f:
                    f.write("# Autonomous fix generated by DeepSeek Coding Agent\n")
                    f.write(fix_data.get("code_changes", "# No code changes provided"))

                print(f"Fix written to {fix_file}")

            # 3. Run tests if provided
            if "test_plan" in fix_data:
                print("🧪 Executing verification tests...")
                # Execute test commands
                pass

            # 4. Create Git commit
            subprocess.run([
                "git", "-C", self.repo_path, "add", "-A"
            ], check=False)

            subprocess.run([
                "git", "-C", self.repo_path, "commit",
                "-m", f"Autonomous fix: {fix_data.get('analysis', 'Code improvement')}"
            ], check=False)

            return True

        except Exception as e:
            print(f"❌ Fix application failed: {e}")
            # Revert on failure
            subprocess.run(["git", "-C", self.repo_path, "reset", "--hard", "HEAD"], check=False)
            return False

if __name__ == "__main__":
    agent = DeepSeekCodingAgent()

    print("🚀 Initializing DeepSeek Coding Agent")
    print("=" * 50)

    # Step 1: Analyze
    analysis = agent.analyze_codebase()
    print(f"📊 Analysis complete. Found {len(analysis['issues_found'])} issues.")

    # Step 2: Fix highest priority issue
    if analysis['issues_found']:
        print(f"\n🎯 Top issue: {analysis['issues_found'][0]}")
        fix = agent.execute_autonomous_fix(analysis['issues_found'][0])

        if "error" not in fix:
            print("\n✅ Fix generated. Applying...")
            success = agent.apply_fix(fix)
            if success:
                print("\n🎉 Autonomous fix successfully applied!")
                print(f"📋 Summary: {fix.get('analysis', 'No summary')}")
            else:
                print("\n⚠️  Fix application failed, changes reverted")
        else:
            print(f"\n❌ Failed to generate fix: {fix['error']}")
    else:
        print("✅ No critical issues found!")