"""
Echo Brain Provider Contract Verification

This test takes the contract JSON generated by the consumer (Vue frontend)
and replays every interaction against the REAL FastAPI application.

If any response doesn't match what the consumer expects → test fails → 
you know the backend has drifted before it breaks production.

Run: pytest test_provider_verification.py -v

IMPORTANT: This imports your actual FastAPI app. Adjust the import path
to match your Echo Brain project structure.
"""

import pytest
import json
import os
import subprocess
import signal
import time
import requests
from pathlib import Path
from provider_states import state_manager


# ─── Configuration ────────────────────────────────────────────────

# Path to the contract generated by consumer tests
CONTRACT_DIR = Path(__file__).parent.parent / 'contracts'

# Import the real Echo Brain FastAPI app
import sys
sys.path.insert(0, '/opt/tower-echo-brain')
from src.main import app as echo_brain_app

# Use the already running Echo Brain service
PROVIDER_HOST = '127.0.0.1'
PROVIDER_PORT = 8309  # use the actual running service port
USE_RUNNING_SERVICE = True  # Set to False to start a test instance


# ─── Test FastAPI App (Replace with real app import) ──────────────

def create_test_app():
    """
    Returns the real Echo Brain FastAPI app for contract verification.

    In test mode, we use the actual app but with provider state
    management endpoints added for Pact testing.
    """
    from fastapi import HTTPException
    from fastapi.responses import JSONResponse
    from datetime import datetime

    # Use the real Echo Brain app
    app = echo_brain_app

    # In-memory state populated by provider state handlers
    _state: dict = {}

    @app.post("/_pact/provider-states")
    async def set_provider_state(body: dict):
        """
        Pact calls this before each interaction to set up the right state.
        Maps the 'given' clause from consumer tests to state handlers.
        """
        nonlocal _state
        state_name = body.get('state', '')
        action = body.get('action', 'setup')

        if action == 'setup':
            _state = state_manager.handle(state_name, body.get('params', {}))
        elif action == 'teardown':
            _state = {}

        return {"status": "ok"}

    @app.get("/api/v1/health")
    async def health():
        return {
            "status": "degraded" if _state.get('vector_status') == 'down' else "healthy",
            "version": "1.2.0",
            "uptime_seconds": 86400,
            "services": {
                "database": {
                    "status": _state.get('db_status', 'up'),
                    "latency_ms": 2.5
                },
                "vector_store": {
                    "status": _state.get('vector_status', 'up'),
                    "latency_ms": 0 if _state.get('vector_status') == 'down' else 5.1
                },
                "ollama": {
                    "status": _state.get('ollama_status', 'up'),
                    "latency_ms": 12.3
                }
            }
        }

    @app.post("/api/v1/query")
    async def query(body: dict):
        if 'query' not in body or not body.get('query'):
            return JSONResponse(
                status_code=422,
                content={
                    "detail": "query field is required",
                    "error_code": "VALIDATION_ERROR",
                    "timestamp": datetime.utcnow().isoformat() + "Z"
                }
            )

        documents = _state.get('seed_documents', [])
        return {
            "results": documents,
            "query_time_ms": 45.2 if documents else 12.1,
            "model_used": "nomic-embed-text",
            "total_matches": len(documents)
        }

    @app.get("/api/v1/memories")
    async def list_memories(page: int = 1, page_size: int = 20):
        memories = _state.get('seed_memories', [])
        return {
            "memories": memories,
            "total": _state.get('total', len(memories)),
            "page": page,
            "page_size": page_size
        }

    @app.post("/api/v1/memories", status_code=201)
    async def create_memory(body: dict):
        return {
            "id": "mem_new_001",
            "status": "created",
            "embedded": True
        }

    @app.get("/api/v1/ingestion/status")
    async def ingestion_status():
        ingestion = _state.get('ingestion', {})
        return {
            "running": ingestion.get('running', False),
            "last_run": ingestion.get('last_run'),
            "last_run_status": ingestion.get('last_run_status'),
            "documents_processed": ingestion.get('documents_processed', 0),
            "documents_failed": ingestion.get('documents_failed', 0),
            "next_scheduled": ingestion.get('next_scheduled'),
        }

    return app


# ─── Provider Verification ────────────────────────────────────────

class TestProviderContract:
    """
    Verify the FastAPI provider satisfies the consumer contract.
    
    Uses pact-verifier CLI to replay interactions. This approach works
    with any Python web framework, not just FastAPI.
    """

    @pytest.fixture(autouse=True)
    def start_provider(self):
        """Use the running Echo Brain service or start a test instance."""
        if USE_RUNNING_SERVICE:
            # Check if the service is already running
            try:
                response = requests.get(f'http://{PROVIDER_HOST}:{PROVIDER_PORT}/health')
                if response.status_code == 200:
                    print(f"Using already running Echo Brain service on port {PROVIDER_PORT}")
                    yield
                    return
            except requests.ConnectionError:
                pytest.skip(f"Echo Brain service not running on port {PROVIDER_PORT}. Start it with: sudo systemctl start tower-echo-brain")
        else:
            # Original test server startup code
            import multiprocessing
            import uvicorn

            app = create_test_app()

            def run_server():
                uvicorn.run(app, host=PROVIDER_HOST, port=PROVIDER_PORT, log_level='error')

            self.server_process = multiprocessing.Process(target=run_server, daemon=True)
            self.server_process.start()

            # Wait for server to be ready
            for _ in range(50):
                try:
                    requests.get(f'http://{PROVIDER_HOST}:{PROVIDER_PORT}/health')
                    break
                except requests.ConnectionError:
                    time.sleep(0.1)
            else:
                raise RuntimeError("Provider server didn't start in time")

            yield

            self.server_process.terminate()
            self.server_process.join(timeout=5)

    def test_provider_satisfies_consumer_contract(self):
        """
        Core verification: replay all consumer interactions against the provider.
        
        This finds the contract JSON in /contracts and verifies each interaction.
        """
        contract_files = list(CONTRACT_DIR.glob('*.json'))

        if not contract_files:
            pytest.skip(
                "No contract files found. Run consumer tests first:\n"
                "  cd consumer && npm test"
            )

        for contract_file in contract_files:
            print(f"\nVerifying contract: {contract_file.name}")

            # Use pact_verifier to check the provider against the contract
            result = subprocess.run(
                [
                    'pact_verifier_cli',
                    '--file', str(contract_file),
                    '--hostname', PROVIDER_HOST,
                    '--port', str(PROVIDER_PORT),
                    '--state-change-url',
                    f'http://{PROVIDER_HOST}:{PROVIDER_PORT}/_pact/provider-states',
                ],
                capture_output=True,
                text=True,
                timeout=60
            )

            print(result.stdout)
            if result.stderr:
                print(f"STDERR: {result.stderr}")

            assert result.returncode == 0, (
                f"Contract verification failed for {contract_file.name}!\n"
                f"This means the FastAPI backend no longer satisfies what "
                f"the Vue frontend expects.\n\n"
                f"Output:\n{result.stdout}\n{result.stderr}"
            )


# ─── Standalone Verification (No pact_verifier_cli) ──────────────

class TestProviderContractManual:
    """
    Manual contract verification using httpx.
    
    Use this if you don't want to install pact_verifier_cli.
    It reads the contract JSON and replays each interaction directly.
    Less thorough than the CLI approach but zero extra dependencies.
    """

    @pytest.fixture(autouse=True)
    def start_provider(self):
        """Start the FastAPI app on a test port."""
        import multiprocessing
        import uvicorn

        app = create_test_app()

        def run_server():
            uvicorn.run(app, host=PROVIDER_HOST, port=PROVIDER_PORT + 1, log_level='error')

        if USE_RUNNING_SERVICE:
            # Use the already running service
            self.base_url = f'http://{PROVIDER_HOST}:{PROVIDER_PORT}'
            try:
                response = requests.get(f'{self.base_url}/api/v1/health')
                if response.status_code != 200:
                    pytest.skip(f"Echo Brain service not healthy on port {PROVIDER_PORT}")
            except requests.ConnectionError:
                pytest.skip(f"Echo Brain service not running on port {PROVIDER_PORT}")
            yield
        else:
            # Start a test server
            self.server_process = multiprocessing.Process(target=run_server, daemon=True)
            self.server_process.start()
            self.base_url = f'http://{PROVIDER_HOST}:{PROVIDER_PORT + 1}'

            for _ in range(50):
                try:
                    requests.get(f'{self.base_url}/api/v1/health')
                    break
                except requests.ConnectionError:
                    time.sleep(0.1)

            yield
            self.server_process.terminate()
            self.server_process.join(timeout=5)

    def _load_contract(self) -> dict:
        """Load the first available contract file."""
        contract_files = list(CONTRACT_DIR.glob('*.json'))
        if not contract_files:
            pytest.skip("No contract files found. Run consumer tests first.")
        with open(contract_files[0]) as f:
            return json.load(f)

    def _replay_interaction(self, interaction: dict):
        """Replay a single interaction from the contract."""
        # Set up provider state
        provider_states = interaction.get('providerStates', [])
        for state in provider_states:
            requests.post(
                f'{self.base_url}/_pact/provider-states',
                json={'state': state['name'], 'action': 'setup'}
            )

        # Build and send the request
        request_data = interaction['request']
        method = request_data['method'].upper()
        path = request_data['path']
        headers = request_data.get('headers', {})
        body = request_data.get('body')

        # Handle query parameters
        query = request_data.get('query', {})
        params = {}
        for key, values in query.items():
            # Pact stores query params as lists
            params[key] = values[0] if isinstance(values, list) else values

        response = requests.request(
            method=method,
            url=f'{self.base_url}{path}',
            headers=headers,
            json=body,
            params=params
        )

        return response

    def test_all_interactions(self):
        """Verify every interaction in the contract."""
        contract = self._load_contract()
        interactions = contract.get('interactions', [])

        if not interactions:
            pytest.skip("Contract has no interactions")

        failures = []
        for interaction in interactions:
            description = interaction['description']
            expected_status = interaction['response']['status']

            try:
                response = self._replay_interaction(interaction)

                # Verify status code
                assert response.status_code == expected_status, (
                    f"Expected {expected_status}, got {response.status_code}"
                )

                # Verify response body structure (keys present)
                if 'body' in interaction['response']:
                    expected_body = interaction['response']['body']
                    actual_body = response.json()
                    self._verify_structure(expected_body, actual_body, description)

                print(f"  ✓ {description}")

            except Exception as e:
                failures.append(f"  ✗ {description}: {e}")
                print(f"  ✗ {description}: {e}")

        if failures:
            pytest.fail(
                f"Contract verification failed!\n"
                f"{len(failures)}/{len(interactions)} interactions failed:\n"
                + "\n".join(failures)
            )

    def _verify_structure(self, expected: any, actual: any, path: str = ""):
        """
        Recursively verify response structure matches contract.
        Checks keys and types, not exact values (that's what matchers are for).
        """
        if isinstance(expected, dict):
            assert isinstance(actual, dict), f"Expected dict at {path}, got {type(actual)}"
            for key in expected:
                assert key in actual, f"Missing key '{key}' at {path}"
                self._verify_structure(expected[key], actual[key], f"{path}.{key}")

        elif isinstance(expected, list):
            assert isinstance(actual, list), f"Expected list at {path}, got {type(actual)}"
            # For non-empty expected lists, verify structure of first element
            if expected and actual:
                self._verify_structure(expected[0], actual[0], f"{path}[0]")
