#!/usr/bin/env python3
"""
Simplified contract verification using the running Echo Brain service.

This script verifies that the Echo Brain API satisfies the contracts
generated by the consumer tests.
"""

import json
import sys
from pathlib import Path
import requests
from typing import Dict, Any, List

# Configuration
CONTRACT_DIR = Path(__file__).parent.parent / 'contracts'
PROVIDER_BASE_URL = 'http://localhost:8309'

def load_contract(contract_file: Path) -> Dict[str, Any]:
    """Load and parse a Pact contract file."""
    with open(contract_file) as f:
        return json.load(f)

def verify_interaction(interaction: Dict[str, Any]) -> tuple[bool, str]:
    """
    Verify a single interaction from the contract.
    Returns (success, message)
    """
    request = interaction['request']
    expected_response = interaction['response']

    # Build the full URL
    url = f"{PROVIDER_BASE_URL}{request['path']}"

    # Prepare headers
    headers = request.get('headers', {})

    # Make the actual request
    try:
        if request['method'] == 'GET':
            if 'query' in request:
                # Add query parameters
                params = request['query']
                actual_response = requests.get(url, headers=headers, params=params)
            else:
                actual_response = requests.get(url, headers=headers)
        elif request['method'] == 'POST':
            body = request.get('body', {})
            actual_response = requests.post(url, headers=headers, json=body)
        else:
            return False, f"Unsupported method: {request['method']}"

    except requests.exceptions.ConnectionError:
        return False, f"Failed to connect to {url}"

    # Check status code
    if actual_response.status_code != expected_response['status']:
        return False, f"Expected status {expected_response['status']}, got {actual_response.status_code}"

    # For successful responses, check the response structure
    if actual_response.status_code == 200 or actual_response.status_code == 201:
        try:
            actual_json = actual_response.json()
            expected_body = expected_response.get('body', {})

            # Basic structure validation (not full Pact matching)
            if not validate_structure(actual_json, expected_body):
                return False, f"Response structure mismatch"

        except json.JSONDecodeError:
            return False, "Response is not valid JSON"

    return True, "OK"

def validate_structure(actual: Any, expected_pattern: Any) -> bool:
    """
    Basic structure validation.
    In a real implementation, this would use Pact's matcher logic.
    """
    if isinstance(expected_pattern, dict):
        if not isinstance(actual, dict):
            return False
        # Check that expected keys exist in actual
        for key in expected_pattern:
            if key not in actual:
                print(f"  Missing key: {key}")
                return False
    elif isinstance(expected_pattern, list):
        if not isinstance(actual, list):
            return False

    return True

def main():
    """Main verification logic."""
    print("\n" + "="*60)
    print("Echo Brain Contract Verification")
    print("="*60)

    # Find contract files
    contract_files = list(CONTRACT_DIR.glob('*.json'))

    if not contract_files:
        print("\n❌ No contract files found.")
        print("   Run consumer tests first: cd consumer && npm test")
        sys.exit(1)

    # Check if service is running
    try:
        health_response = requests.get(f"{PROVIDER_BASE_URL}/health")
        if health_response.status_code != 200:
            print(f"\n❌ Echo Brain service not healthy")
            sys.exit(1)
        print(f"\n✅ Echo Brain service is running on {PROVIDER_BASE_URL}")
    except requests.exceptions.ConnectionError:
        print(f"\n❌ Cannot connect to Echo Brain service at {PROVIDER_BASE_URL}")
        print("   Start it with: sudo systemctl start tower-echo-brain")
        sys.exit(1)

    # Verify each contract
    all_passed = True
    total_interactions = 0
    passed_interactions = 0

    for contract_file in contract_files:
        print(f"\n📄 Contract: {contract_file.name}")
        contract = load_contract(contract_file)

        interactions = contract.get('interactions', [])
        print(f"   Found {len(interactions)} interactions to verify")

        for i, interaction in enumerate(interactions, 1):
            description = interaction.get('description', 'Unknown')
            request = interaction['request']

            print(f"\n   [{i}/{len(interactions)}] {description}")
            print(f"       {request['method']} {request['path']}")

            success, message = verify_interaction(interaction)
            total_interactions += 1

            if success:
                print(f"       ✅ {message}")
                passed_interactions += 1
            else:
                print(f"       ❌ {message}")
                all_passed = False

    # Summary
    print("\n" + "="*60)
    print(f"Results: {passed_interactions}/{total_interactions} interactions passed")

    if all_passed:
        print("✅ All contract tests passed!")
        print("   Frontend and backend are in sync.")
    else:
        print("❌ Some contract tests failed.")
        print("   The Echo Brain API does not fully satisfy the consumer contract.")
        sys.exit(1)

if __name__ == '__main__':
    main()